# Generated by Django 4.2.9 on 2024-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('port', models.CharField(max_length=5)),
                ('protocol', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('uptime', models.CharField(max_length=10)),
            ],
        ),
    ]
